export type DiscoveryPage = { slug: string; title: string; description: string; sections: { title: string; paragraphs: string[] }[]; sources?: { title: string; url: string }[]; published?: string; author?: string; kind?: "research" | "update" | "platform" };

export const sources = {
  faa: { title: "FAA: Advanced UAS operations", url: "https://www.faa.gov/uas/advanced_operations" },
  delivery: { title: "FAA: Package delivery by drone (Part 135)", url: "https://www.faa.gov/uas/advanced_operations/package_delivery_drone" },
  nist: { title: "NIST: Ground robot test methods", url: "https://www.nist.gov/el/intelligent-systems-division-73500/standard-test-methods-response-robots/ground-robot-tests" },
  radio: { title: "NIST: Response robot performance under attenuated radio conditions", url: "https://doi.org/10.6028/NIST.IR.8243" },
  aed: { title: "NEJM: Use of a drone-delivered AED in an out-of-hospital cardiac arrest", url: "https://www.nejm.org/doi/abs/10.1056/NEJMc2200833" },
  cares: { title: "CARES: 2024 annual report, response-time analysis", url: "https://beta.mycares.net/sitepages/uploads/2025/2024_flipbook/inc/html/37.html" },
};

const stage = "MARDE Inc. is a Delaware C-Corporation based in New Jersey, with an initial institutional focus on New Jersey and the Northeast United States. It is pre-seed, pre-prototype and pre-revenue. There are no deployed systems, commercial pilots or validated full-system performance results. The next milestone is an integrated, human-in-the-loop V1 demonstration. This page describes development objectives, not an available emergency-response service.";

const platforms = [
  { id: "air", name: "Air", role: "Aerial transport for emergency-response robotics", intro: "MARDE Air is the proposed aerial transport component of an integrated response platform. Its intended job is to carry Ground and its response payload toward a scene, then support a planned transition into ground access. Air is not being presented as a standalone, commercially available delivery drone. Aircraft geometry, payload integration and flight performance remain engineering questions.", questions: "Air engineering must investigate the combined mass of Ground, its payload and the transport interface. Payload mass changes flight behavior, energy requirements and landing options. No payload capacity, endurance, range, launch time or weather envelope is published as an achieved MARDE result. Those values require a defined configuration, repeatable tests and explicit operating conditions before they can guide an agency decision.", handoff: "Aerial arrival is only one event in the proposed workflow. A landing or release location must also support the next ground movement. An aircraft may reach a geographic point while leaving the payload too far from a patient, behind a barrier or at a location that an operator cannot safely assess. Air development therefore needs to consider the handoff location and retrieval process alongside flight planning.", tests: "A useful Air evaluation would document payload configuration, launch preparation, operator involvement, flight conditions, landing accuracy and the completeness of the Air–Ground handoff. An integrated demonstration should record failed and aborted attempts, not only successful arrivals. Before any operational evaluation, MARDE and relevant partners would need an applicable aviation pathway and a defined safety plan.", refs: [sources.faa, sources.delivery] },
  { id: "ground", name: "Ground", role: "Teleoperated ground robotics for final emergency access", intro: "MARDE Ground is the proposed final-access component of the platform. It is intended to continue an approach after aerial transport, carrying a response payload toward the place where it could be useful. V1 is teleoperated first: an operator directs movement rather than an autonomous system making independent medical decisions. Mobility through terrain and constrained spaces remains a design objective.", questions: "Ground engineering must investigate clearance, traction, stability, payload retention, power use and recovery after a stopped mission. Stairs, thresholds, loose surfaces and narrow passages represent different challenges; success on one does not establish capability on another. MARDE has not published measured stair-climbing capability, obstacle clearance, speed or operating duration. A defensible specification would identify the tested surface, load and operator conditions.", handoff: "The last part of an approach can be harder to observe than the flight. Doors may be closed, indoor layouts may be unknown, people may be nearby and communications may weaken. Reaching a building is different from reaching a patient. The proposed operator workflow needs to support stopping, reassessing and handing responsibility back to responders when access cannot be established safely.", tests: "Ground evaluation should use repeatable tasks rather than promotional demonstrations. NIST response-robot test methods provide a reference for thinking about mobility, operator proficiency and communication constraints. MARDE would need to choose relevant tasks, publish conditions and record interventions, unsuccessful attempts and recovery time. Referencing these methods does not mean that Ground has passed them or received NIST certification.", refs: [sources.nist, sources.radio] },
  { id: "nexus", name: "Nexus", role: "Human-in-the-loop command software for Air–Ground coordination", intro: "MARDE Nexus is the proposed command and coordination layer connecting operators, Air, Ground and response workflows. Its purpose is to make mission context, system readiness and transitions understandable to a person responsible for consequential decisions. The website interface is illustrative. It is not connected to aircraft, patient information, emergency dispatch or a live command system.", questions: "Nexus engineering must investigate the information an operator needs before an action, how current that information is and how uncertainty is displayed. A readiness label is useful only if its source and limitations are clear. Communication loss, stale telemetry, ambiguous location and competing alerts need defined handling. MARDE has not published measured control latency, availability, integration coverage or operator workload results.", handoff: "Coordination means more than showing several vehicles on a screen. The person controlling Air may need to confirm that Ground can proceed, that the payload remains secured and that a handoff location is understood. An agency also needs to know who may stop the mission and how responsibility transfers to professional responders. These are proposed workflow requirements to investigate with practitioners.", tests: "A useful Nexus evaluation would measure operator understanding, missed alerts, mistaken authorizations, time to recover from communication loss and clarity of the handoff record. Controlled exercises should include interrupted and rejected missions. There is no public operational robot-control API or deployable Nexus software offered through this website. Research and requirements conversations should use the existing Contact page.", refs: [sources.nist, sources.radio] },
  { id: "modules", name: "Intervention Modules", role: "Modular response payloads for an integrated robotics platform", intro: "MARDE Intervention Modules describe an adaptable payload architecture within the proposed Air–Ground response system. Near-term work focuses on delivery, secure-response functions and integration. Modules are not current treatment capabilities. A future medical payload would need its own engineering, clinical, operational and regulatory evaluation, as well as a clear role for professional responders.", questions: "Module engineering must investigate attachment, retention, identification, power needs, environmental protection and retrieval. A payload that is transported successfully still needs to remain usable after arrival. Requirements may differ substantially between a sealed supply package and equipment intended for a trained responder. MARDE has not published validated payload interfaces, compatibility lists, medical performance or sterilization results.", handoff: "Payload delivery does not establish patient benefit by itself. Someone must locate the payload, understand its intended use and complete an appropriate handoff. Access, packaging and communication therefore belong in the evaluation, alongside transport. The proposed modular approach should preserve clear boundaries between robot operation, equipment use and professional clinical judgment.", tests: "Module evaluation should document retention during movement, condition after transport, identification accuracy, accessibility and the receiving person's understanding. Any future clinical capability requires evidence beyond a robotics demonstration. Published drone-AED work helps frame questions about delivery and retrieval, but it is evidence about another system and setting, not validation of a MARDE module.", refs: [sources.aed, sources.nist] },
];

export const discoveryPages: DiscoveryPage[] = [
  ...platforms.map(p => ({ slug: `technology/${p.id}`, title: `MARDE ${p.name}: ${p.role}`, description: p.intro, kind: "platform" as const, sources: p.refs, sections: [
    { title: p.role, paragraphs: [p.intro, stage] },
    { title: "Where it fits in the intended response", paragraphs: ["The conceptual sequence is professional dispatch, Nexus operator review, Air transport, Ground approach, payload delivery and EMS handoff. This is an architecture being developed, not a description of an existing dispatch integration. Each transition needs a responsible person, a known system state and a way to stop when assumptions no longer hold.", p.handoff] },
    { title: "Human oversight comes first", paragraphs: ["V1 is intended to remain human-in-the-loop. Consequential actions require operator authorization, and the overall system is intended to complement EMS rather than replace clinicians or responders. Higher autonomy is a possible future direction that depends on measured reliability and appropriate evaluation. A concept drawing or interface illustration does not establish safe operation.", "Requirements conversations should distinguish who operates the system, who accepts the payload and who makes clinical decisions. These responsibilities may involve different people. The proposed workflow needs explicit boundaries and a practical fallback when the mission cannot continue. An emergency-response concept must remain useful to professionals even when the robotic component is unavailable."] },
    { title: "Open engineering questions", paragraphs: [p.questions, "Testing needs to connect the subsystem to the rest of the architecture. A component can succeed in isolation while the combined workflow fails because of timing, packaging, communications or a confusing handoff. MARDE's immediate goal is to investigate those interactions in a controlled integrated demonstration before making claims about operational use."] },
    { title: "Evidence needed before evaluation", paragraphs: [p.tests, "Agency evaluation should start with a written use case and success criteria agreed before testing. Records should distinguish design targets, bench observations, integrated exercises and operational outcomes. Changing a configuration or setting can invalidate a previous result. Published evidence should therefore describe limitations, exclusions and the circumstances under which a conclusion applies."] },
    { title: "Discuss requirements with MARDE", paragraphs: ["MARDE welcomes institutional conversations with EMS agencies, fire departments, municipalities, researchers and public-safety teams. Useful input includes access barriers, operator responsibilities, dispatch constraints and acceptable evaluation conditions. The initial regional focus is New Jersey and the Northeast United States; this describes research interest, not service coverage.", "Use the Contact page to discuss requirements or future evaluation opportunities. Do not send patient records or request live emergency assistance through the website. No price, purchase offer, deployment date or pilot commitment is implied by this page. The appropriate next step is a factual discussion about what would need to be built and demonstrated."] },
  ] })),
  { slug: "about", title: "About MARDE Inc.", description: "Emergency-response robotics in development in New Jersey, with an initial focus on the Northeast United States.", sections: [
    { title: "The company and its purpose", paragraphs: [stage, "MARDE is investigating how coordinated robotics could extend useful capability into the interval before professional responders arrive. Its proposed architecture combines Air for distance, Ground for final access, Nexus for human coordination and Intervention Modules for adaptable payloads. The goal is to complement EMS workflows and make the eventual handoff explicit."] },
    { title: "People, evidence and accountability", paragraphs: ["The public Team page describes the people and responsibilities behind the work. MARDE's current direction is to build and integrate Air V1, Ground V1 and Nexus V1, then generate evidence through controlled testing. External research helps frame the problem; it does not establish MARDE performance. Technical specifications and future medical capabilities must follow validation rather than precede it.", "For research, institutional requirements, investment or advising conversations, contact team@mardeinc.com or use the Contact page. The website is an information and inquiry channel, not an emergency service or an operational command interface. Public contact details and development-stage statements are intended to make the company's current position easy to verify."] },
  ] },
  { slug: "ems-partners", title: "EMS and public-safety research conversations", description: "Help define requirements for emerging emergency-response robotics before any operational evaluation.", sources: [sources.nist, sources.faa], sections: [
    { title: "Start with a workflow, not a deployment promise", paragraphs: [stage, "MARDE welcomes conversations with EMS agencies, fire departments, medical directors and municipalities about response gaps and access constraints. We are seeking practical requirements and technical feedback. This page does not announce signed partnerships, funded pilots, dispatch integration or a system available for clinical use."] },
    { title: "Questions worth bringing to the table", paragraphs: ["Where does access become difficult after a vehicle reaches the scene? Who could receive a delivered payload? What information would an operator need, and who would authorize movement? Which environments should be excluded? Discussing these questions helps define an evaluation that is useful to responders rather than a demonstration optimized for a video.", "Requirements should address staffing, training, communications, aborted missions and the handoff to professional care. Participants should identify what a robot must never assume about patient location, building access or clinical need. Agencies can share de-identified scenarios and general operational constraints without disclosing patient records."] },
    { title: "A staged evaluation", paragraphs: ["The proposed sequence is requirements discovery, controlled subsystem testing, integrated exercises and only then consideration of future operational evaluation. Each stage needs agreed success criteria and a record of failures as well as successes. Any later pilot would require separate scope, responsibilities, applicable approvals and an evidence-based readiness decision.", "Contact MARDE to discuss your role, organization and the problem you would like to explore. Existing email and contact-form channels are the appropriate starting point. There is no public mission API, live emergency service or automated enrollment into a pilot."] },
  ] },
  { slug: "updates", title: "MARDE development updates", description: "Documented status and future evidence from the integrated emergency-response robotics program.", sections: [
    { title: "Current public development status", paragraphs: [stage, "This page records the public development position rather than announcing an engineering milestone. No completed prototype, successful flight, clinical outcome or partner deployment is claimed. Future updates will identify what changed, the configuration or conditions involved and the limitations of the available evidence."] },
    { title: "What future updates will report", paragraphs: ["Meaningful updates may cover requirements discovery, subsystem work, integration exercises or repeatable test results. Reports should distinguish plans from observations and identify unsuccessful attempts when relevant. An update will receive a publication date when documented progress is available; a calendar alone is not evidence of progress."] },
  ] },
];
