// Original proposed exercises, explicitly hypothetical; not external findings.
export const researchExercises: Record<string, { title: string; paragraphs: string[] }[]> = {
  "research/drone-aed-evidence": [
    { title: "A hypothetical retrieval exercise", paragraphs: [
      "Consider a controlled exercise in which an inert training payload is delivered to a designated receiving area. No patient is involved and no clinical result is measured. The receiving participant knows the exercise rules but does not receive advance knowledge of the exact placement. Observers record arrival, identification, retrieval and receipt at the agreed endpoint. The question is whether the transport-to-retrieval process is understandable under the stated conditions.",
      "Repeat the exercise with a changed receiving location, an unavailable receiver and an interrupted notification. These variations investigate different failure paths rather than simulating a medical emergency. The team should predefine when the exercise stops and how the payload is recovered. If an observer needs to explain where to go or how to retrieve the package, count that intervention rather than quietly treating the task as unassisted success.",
      "The report should describe packaging, participant preparation, notification method and the boundaries of the receiving area. It should distinguish a package being present from a participant recognizing and retrieving it. If the receiving task works only with trained participants in a cleared outdoor area, say so. That result can guide another test without being extended to an untrained bystander or an unfamiliar building.",
    ] },
    { title: "Questions that remain after a transport test", paragraphs: [
      "Even a repeatable retrieval result leaves important questions open. Would the proposed mission be eligible and available under real operating conditions? Would retrieval interfere with other actions? Which responder or bystander role is appropriate? How should clinical equipment be handled? Those questions require practitioners, qualified evaluators and, where appropriate, clinical study design. A robotics team should identify them rather than pretending its transport test answers them.",
      "A useful evidence table can list the claim, supporting observation, conditions and unresolved next step. For example, a successful training-payload retrieval supports that defined task in the exercise setting. It does not support a claim about patient outcomes or network-wide response reliability. Keeping the table public makes it easier for an agency to understand why additional evidence is needed.",
      "MARDE's eventual integrated test would add an Air–Ground transition to this chain. That introduces its own potential delays and failures, so the result should be compared with the intended task, not assumed to improve on direct delivery. If Ground adds complexity without enabling useful access, the evaluation should reveal that. The point of a staged program is to learn which configuration merits further investigation.",
      "Keep the original source available beside any summary. Readers should be able to distinguish the published case from MARDE's proposed exercise and inspect the evidence without relying on a marketing paraphrase.",
    ] },
  ],
  "research/final-access": [
    { title: "Turn broad access claims into a task record", paragraphs: [
      "A task record can describe the starting point, receiving point, route conditions, payload and operator preparation in ordinary language. Add photographs or drawings of the controlled layout when publishing an eventual result, while avoiding sensitive operational locations. Record the configuration identifier and which parts changed since the preceding exercise. These details make it possible to compare attempts and prevent a later reader from assuming that a result applies to every building or terrain type. The record should also state what was intentionally excluded, including occupied rooms, unknown doors or conditions outside the test plan.",
      "A separate interpretation can then explain what the team believes the result suggests. For example, a recurring stop at a threshold might motivate a mechanical change, a camera change or a revised exclusion. The observation alone may not identify which change is best. Treat the explanation as a hypothesis and define another exercise that can distinguish the possibilities. This keeps access engineering connected to evidence instead of letting a successful or unsuccessful video drive a broad product claim. MARDE has not completed the task record described here; it is a proposed reporting approach for future work.",
    ] },
    { title: "A hypothetical corridor-to-receiver test", paragraphs: [
      "Imagine a controlled training area with a marked aerial handoff point, a ground route and a receiving station. Use an inert payload and keep people outside the vehicle path. Before the attempt, document route width, surface, obstacles, lighting and operator location. The target is receipt at the marked station, not entry into an unknown occupied space. This creates a bounded access question that can be repeated.",
      "A first configuration might test a clear route, followed by a configuration with a documented threshold or turn. The operator should receive only the information intended to be available in the proposed system. If someone standing near the robot provides extra directions, record the help. Repeatability depends on controlling these details; otherwise two apparently similar attempts can rely on very different levels of human assistance.",
      "Record task completion, elapsed time, stops, interventions and payload condition. Also record the reason for an unsuccessful attempt: insufficient clearance, loss of observation, inability to move or an operator decision to stop. These categories help determine what to change next. A single completion percentage without its task definition tells a practitioner little about relevance to another scene.",
    ] },
    { title: "Recovery is part of the access requirement", paragraphs: [
      "An exercise should include a blocked receiving point. The operator may need to stop, return or leave the payload at an agreed safe location. Which response is appropriate depends on the use case and system design, so the choice belongs in the protocol. It should not be improvised during a demonstration and later described as a reliable recovery capability.",
      "A useful recovery record identifies who notices the problem, what information they have and who retrieves the system if movement cannot continue. It also identifies whether recovery occupies people needed elsewhere. This helps agencies evaluate staffing consequences instead of considering only vehicle dimensions. A robot that is easy to send but difficult to recover may impose an unacceptable operational burden.",
      "After testing, compare the result with the original access problem. If the receiving station was already reachable by a simpler arrangement, the exercise may establish engineering progress without establishing operational value. If the task addresses a genuine barrier, the next exercise should investigate the remaining limitations. MARDE should communicate both possibilities as part of an honest development record.",
    ] },
  ],
  "research/human-oversight": [
    { title: "Separate responsibility from interface visibility", paragraphs: [
      "Showing an action to a person does not necessarily give that person the information or authority needed to manage it. A requirements document should distinguish observation, approval, direct control and acceptance of a handoff. One role may perform several of these functions, but the arrangement must be stated. During a prototype exercise, ask which participant believes they can stop the sequence and whether others agree. Conflicting answers are evidence of an unresolved workflow, even if the interface itself has no technical errors. Resolve the responsibility question before treating a control as an operational safeguard.",
      "A software team can document the intended role beside each proposed control and explain which prerequisites are checked automatically, asserted by a user or unknown. This is also a way to avoid presenting a readiness indicator as more authoritative than its underlying information. Later testing should investigate how operators interpret those distinctions. If a participant assumes that a green label means a receiving person is available when that fact was never checked, the wording or workflow needs attention. MARDE's website mockup is a communication tool for discussing these requirements, not a validated authorization mechanism or a demonstration of live control.",
    ] },
    { title: "A hypothetical authorization exercise", paragraphs: [
      "A useful early software exercise can occur without any moving robot. Present a participant with simulated mission context and an action requiring review. Include scenarios with complete information, stale readiness information and a missing receiving arrangement. Ask the participant to explain whether they would authorize the transition and why. The exercise evaluates understanding of a proposed interface, not operational control or clinical competence.",
      "Decide in advance which facts are relevant and which choices should lead to a pause. Do not score participants against rules invented after observing their responses. Record the time needed to find information, mistaken interpretations and requests for clarification. A disagreement may indicate ambiguous requirements rather than operator error. Interface evaluation is useful precisely because it can uncover those gaps before hardware integration.",
      "Repeat selected scenarios after changing how uncertainty is displayed. The team can compare comprehension without claiming that a prettier layout produces safer missions. The eventual operational setting may introduce workload, training and communication constraints absent from the exercise. Report those exclusions with the result so readers understand which question was actually investigated.",
    ] },
    { title: "Keep an authorization record that means something", paragraphs: [
      "An authorization record should identify the action and context reviewed, not merely that a button was pressed. For a prototype exercise, researchers can document the simulated system state, the participant's decision and any missing information. A future operational record would require separate decisions about privacy, retention and access. Do not introduce patient information into an early interface study just to make the display appear realistic.",
      "Handoffs can be investigated with two participants responsible for different parts of the sequence. The receiving participant should explain what they believe has happened and what authority they now have. If the two interpretations differ, the system has not established shared understanding simply because both users saw the same status label. Test the words and decision boundaries as carefully as the controls.",
      "For MARDE, such exercises would inform Nexus requirements while preserving a clear development-stage boundary. No completed operator study is claimed here. Before presenting any future findings, the team should identify participants' preparation, scenario definitions and the assistance provided. An evaluation framework is a way to generate evidence, not evidence that the proposed interface is already effective.",
    ] },
  ],
  "research/aviation-pathway": [
    { title: "Describe the boundaries of a flight-related claim", paragraphs: [
      "A public report about an eventual flight should identify whether it concerns a component, an integrated configuration or an operational exercise. State the setting and constraints in terms a reader can understand. If a task used a controlled site, nearby support personnel or a limited route, those facts belong with the conclusion. Do not imply that completing the exercise establishes availability over a wider region. An honest report can still communicate engineering progress while making clear that different airspace, payload or receiving conditions may require additional work and review. The same discipline should apply to images and video captions.",
      "Future product language should also avoid conflating the company, the aircraft and the operation. An authorization may concern a defined activity rather than every system the company plans to build. A measured aircraft property may concern one configuration rather than an entire platform family. Linking each statement to its supporting record allows an agency to ask the right follow-up question. Until those records exist, MARDE should discuss requirements and development objectives. Its New Jersey location and Northeast research interest do not establish an approved operating area, a delivery network or the availability of a response mission at any particular address.",
    ] },
    { title: "Build an operation-specific questions register", paragraphs: [
      "Before seeking advice about an eventual flight, prepare a concise operation description. Identify what the aircraft carries, where it might operate, who controls it and what movement occurs after landing or release. Mark unmeasured values as unknown. A reviewer cannot evaluate a broad promise of emergency delivery as reliably as a bounded proposal with explicit conditions and unanswered engineering questions.",
      "The questions register should connect each uncertainty to the information needed to resolve it. If aircraft mass is not established, record that fact rather than assuming the lightest possible configuration. If the receiving location is unknown, explain how location selection would work. If an operator is expected to supervise more than one task, describe the workload assumption. These are facts to investigate, not opportunities for optimistic defaults.",
      "When authoritative guidance is obtained, record its date and the specific proposal it addressed. A changed payload, operating area or mission may require renewed review. Avoid converting advice about a narrow controlled exercise into a general statement that the company is approved. Public communication should use wording that matches the actual scope of the evidence and permission.",
    ] },
    { title: "A hypothetical readiness review before a demonstration", paragraphs: [
      "For a proposed controlled demonstration, a readiness review could ask whether the configuration is documented, the site is appropriate, relevant permissions are established and all participants understand stopping criteria. It should also ask how the system is recovered and how the conventional institutional workflow remains unaffected. This is an example of planning questions, not a completed MARDE review or a universal regulatory checklist.",
      "Keep engineering and operational evidence in separate records linked to the same configuration. A flight log may describe behavior; a permission record addresses the allowed operation. The report should identify both without implying that one establishes the other. If an exercise is canceled because a prerequisite is missing, that decision is part of responsible progress and should not be hidden behind a launch announcement.",
      "An agency considering a later evaluation needs enough information to assess its own role and obligations. That includes staffing assumptions, receiving arrangements, exclusions and the boundaries of the company's claims. MARDE's public pages should remain useful during this process by identifying what is known and linking to current primary guidance. They should not promise eligibility for a pathway before a defined operation has been reviewed.",
    ] },
  ],
  "research/response-gap": [
    { title: "Make a response statistic easy to audit", paragraphs: [
      "A useful citation record includes the report year, table or page, event definition, population and exclusions. Keep those details with the number when adapting it to a presentation or another website page. If the source revises its analysis, the team can then identify which public statements need review. A source URL alone may not preserve the meaning of a statistic when a reader sees only a cropped chart or social post. MARDE's response-gap discussion should remain traceable to the original CARES material and should identify the numbers as historical registry findings rather than a current local forecast.",
      "Readers should also distinguish a reason to study a problem from evidence that a proposed solution addresses it. A response interval can motivate investigation of earlier equipment access, but the proposed system may introduce its own review, transport and receiving delays. It may be unavailable in conditions where professional response still proceeds. These considerations do not make the research question unimportant; they define what an honest evaluation must measure. A future MARDE report should preserve the external statistic's scope and present its own observations separately, with no implied subtraction or clinical conclusion unless an appropriate study actually supports that interpretation.",
    ] },
    { title: "A hypothetical timeline exercise", paragraphs: [
      "A team can investigate timing definitions before calculating any projected advantage. Draw two timelines: the existing institutional workflow and the proposed robotic workflow. Mark observed events, assumed intervals and missing information differently. Do not assign a MARDE performance number to an interval that has never been measured. This exercise makes it easier to see whether the proposal addresses transport, access, payload receipt or another task.",
      "Next, examine whether the start and end points represent equivalent events. A transport interval beginning after operator approval omits review time. An arrival interval ending outside a building omits final access. A registry interval starting at call receipt may include steps absent from a robotics exercise. These differences do not make a comparison impossible, but they must be resolved or disclosed before using it to support a claim.",
      "The team can then identify which observations would reduce the most uncertainty. A controlled test may measure a handoff delay while leaving dispatch eligibility unresolved. A practitioner conversation may clarify a receiving role without establishing aircraft reliability. Treating these as distinct contributions allows the program to make progress without presenting a complete operational model prematurely.",
    ] },
    { title: "What a useful future timing report would contain", paragraphs: [
      "A future report should state the configuration, setting and task definition before showing its summary values. It should identify the number of attempts and explain missing timestamps. Separate completed tasks from interrupted and rejected tasks, while keeping all of them visible. If manual intervention changes the timeline, record when it occurred and what assistance was provided. Readers need this context to interpret even a seemingly straightforward median.",
      "Avoid displaying decimal precision that exceeds the quality of the observations. More digits do not repair ambiguous start points or incomplete records. If results vary substantially, show the variation and conditions rather than selecting the fastest attempt. The purpose is to help an agency judge whether another evaluation is worthwhile, not to manufacture a favorable comparison with a national population statistic.",
      "For clinical questions, timing evidence is only one part of the evaluation. Whether equipment is usable, whether the receiving process is appropriate and whether outcomes change require different observations and expertise. MARDE should keep those claims separate in its research library and future updates. CARES helps motivate investigation of the interval; it cannot stand in for a measured robotic or clinical result.",
    ] },
  ],
  "research/evaluating-early-stage-partners": [
    { title: "Use a decision record instead of a vendor score alone", paragraphs: [
      "An agency can keep a short record of the decision being considered, the evidence available and the reason for the next step. The decision might be whether to continue requirements discovery, observe a controlled demonstration or decline a proposed configuration. These are different commitments and should not be compressed into a general positive assessment of the company. A record can identify unresolved questions without demanding that every early-stage uncertainty be solved immediately. It also gives future reviewers context when personnel change or when a later proposal differs from the one initially discussed. Keep private institutional information under the agency's own controls.",
      "The company can maintain a corresponding public claim register that identifies what it is willing to say and what remains unvalidated. The two records need not contain the same confidential details to support a clear conversation. A useful outcome is agreement on the next question and the evidence that would answer it, including a reason to stop if the approach proves unsuitable. MARDE's initial conversations should be framed this way. Participation in discovery should not be described as a sale, partnership endorsement or operational pilot unless the organization has separately agreed to that relationship and its public description.",
    ] },
    { title: "A hypothetical first requirements meeting", paragraphs: [
      "An agency and an early-stage team can begin with one de-identified access scenario. The agency explains where useful equipment would need to arrive and what currently prevents that arrival. The company explains which parts of its concept might address the problem and which are still unknown. Neither side needs to promise procurement or clinical use for the discussion to produce a meaningful requirements document.",
      "At the end of the meeting, write down the proposed receiving point, responsible roles and the conditions that would make an exercise inappropriate. Identify the existing alternative and the improvement that would matter. Then list the evidence required before considering another stage. This prevents a broad statement of interest from being represented publicly as a partnership or a deployment commitment.",
      "A follow-up exercise should be narrow enough that both parties understand what its result means. If the question is whether an operator can deliver an inert payload through a defined route, do not add clinical claims to the report. If the result reveals an access barrier the concept cannot address, that is a useful finding. A requirements program should be able to conclude that a proposed configuration is not suitable.",
    ] },
    { title: "Review the report before moving to another stage", paragraphs: [
      "Ask whether the report includes all attempts, the assistance provided and changes made during testing. Compare its conclusions with the agreed success criteria. Distinguish a documented observation from an explanation of why the team believes it occurred. Both may be useful, but only the observation directly describes what the exercise established. An agency can request clarification without asking the company to disclose unrelated proprietary details.",
      "Before expanding the evaluation, agree on the next unresolved question and why it matters to the operational problem. Increasing realism is not automatically useful if a more basic assumption remains unsupported. For example, moving to a larger site may add complexity while leaving the receiving role unclear. A staged program should spend effort on the uncertainty that affects the next decision.",
      "Public communication also deserves review. An agency's participation in a requirements conversation is different from endorsement, customer status or permission to use its name. MARDE should obtain appropriate authorization before describing another organization in an update. A transparent record can still describe the work performed and its limitations without inventing institutional support. That discipline strengthens credibility for future readers and potential evaluators.",
    ] },
  ],
};
