import { sources, type DiscoveryPage } from "./discovery";
import { researchExercises } from "./research-exercises";

const boundary = "This article is MARDE's research perspective on evaluation questions, not a report of MARDE test results. MARDE is pre-prototype and has no deployed emergency-response system. External evidence concerns the systems and settings studied by its authors. The proposed MARDE architecture still needs engineering, integrated testing and applicable approvals.";

export const researchPages: DiscoveryPage[] = [
  {
    slug: "research/drone-aed-evidence", title: "Drone AED delivery: what evidence can and cannot establish", description: "Separate aerial delivery, retrieval, clinical use and patient outcomes when evaluating drone AED evidence.", sources: [sources.aed],
    sections: [
      { title: "Delivery is a step in a longer chain", paragraphs: ["Drone delivery of an automated external defibrillator raises a practical question: can equipment become usable sooner than it otherwise would? That question contains several distinct events. Dispatch must recognize a suitable situation, a flight must be possible, the device must reach a usable location and someone must retrieve it. Clinical use and patient outcomes come later. Collapsing the entire chain into a single arrival-time statistic hides where a response can fail.", "A published New England Journal of Medicine report describes use of a drone-delivered AED in an out-of-hospital cardiac arrest. It provides a concrete example of delivery and retrieval leading to use in a particular setting. A case report does not establish the reliability, effect size or general applicability of an entire delivery network. Its value is partly in making the real chain of events visible."] },
      { title: "Read the denominator before the headline", paragraphs: ["A careful review asks which suspected emergencies were considered, how many were eligible, how many resulted in a launch and how many produced a delivered and retrieved device. Weather exclusions, airspace restrictions, inaccurate locations and unavailable receiving people may affect different parts of that chain. A time advantage among successful flights is not necessarily the time advantage across all eligible calls.", "For an agency, the useful denominator depends on the decision. A flight team may need reliability per launch. A dispatch organization may need coverage per eligible call. A clinical evaluation may need equipment use or outcomes among patients who could benefit. Those measures answer different questions and should be presented together rather than substituted for one another."] },
      { title: "Arrival, retrieval and use need separate timestamps", paragraphs: ["An evaluation protocol should define what arrival means. The aircraft reaching coordinates, the payload touching the ground, a person picking it up and the equipment reaching a patient are different events. The interval between those events can determine whether a transport advantage becomes useful. Teams should decide which timestamps can be observed reliably and how missing observations will be recorded.", "A receiver may need instructions about where a payload landed, how to recognize it and whether retrieving it would interrupt another essential action. This article does not prescribe clinical behavior. It identifies a workflow question for qualified responders and medical oversight: what receiving process makes equipment available without creating another burden or unsafe instruction?"] },
      { title: "Transport evidence does not validate final access", paragraphs: ["A delivery location may be outdoors while a patient is behind a door or on another level. That is a separate access problem. MARDE's proposed Ground component explores continuing beyond aerial arrival under operator direction, but that proposal does not solve the problem by definition. Terrain, communication, payload retention and human interaction would all require their own evidence.", "The same distinction applies to payload design. An AED is established equipment in its appropriate use context, but attaching it to a new transport platform raises questions about packaging, condition after movement and retrieval. Evidence about one aircraft or delivery arrangement cannot automatically be transferred to another configuration."] },
      { title: "Design an evaluation around failure as well as success", paragraphs: ["Before an exercise, define the operating envelope, receiving role, abort criteria and outcome measures. Record canceled missions and unsuccessful retrievals alongside completed deliveries. Document changes in hardware, software and packaging so a result remains connected to the configuration tested. A demonstration that excludes difficult conditions should describe those exclusions prominently.", "A prospective comparison also needs an appropriate baseline. The relevant comparison is not always drone versus ambulance arrival; it may involve nearby equipment, other responders or existing access arrangements. Qualified study designers should choose the comparison and clinical endpoints. MARDE should not infer a survival benefit from a conceptual time saving or an unrelated registry statistic."] },
      { title: "Questions for agencies and researchers", paragraphs: ["Ask where a device would be placed, who would receive it, how the receiver would be contacted and what happens if no one can retrieve it. Ask whether the published sample resembles the intended operating environment and whether all relevant exclusions are visible. Ask which claim is supported: feasible delivery, earlier retrieval, successful use or improved clinical outcomes.", "For MARDE, the immediate purpose of this literature is requirements discovery. An integrated V1 demonstration would investigate the transport-to-access handoff under controlled conditions. It would not itself establish clinical effectiveness. Readers can use the source below to inspect the reported example and use the EMS Partners page to discuss the questions an eventual evaluation would need to answer.", boundary] },
    ],
  },
  {
    slug: "research/final-access", title: "The final-access problem after aerial arrival", description: "Why arrival at coordinates and useful access to a scene are different robotics requirements.", sources: [sources.nist, sources.radio],
    sections: [
      { title: "Coordinates are not an access plan", paragraphs: ["A vehicle can arrive at the right location while its payload remains inaccessible. A fence, threshold, stair, closed door or uncertain receiving point can separate geographic arrival from useful delivery. The final-access problem is the set of tasks required to move from that arrival point to a place where an authorized person can receive or use the payload.", "For MARDE, Ground is the proposed component for investigating that continuation. It is intended to be teleoperated first, with a human directing the approach. This is an architectural objective, not a claim that MARDE already traverses stairs or enters buildings. The first useful step is to break broad access language into testable tasks."] },
      { title: "Describe the obstacle precisely", paragraphs: ["A requirement such as handles stairs is incomplete. An evaluation needs dimensions, surface conditions, landing space, payload configuration and operator visibility. A robot that moves successfully on one arrangement may fail on a different height, edge shape or surface. Similar care applies to doorways and narrow passages: clearance alone does not establish that the operator can navigate safely.", "Agencies can help by describing recurring barriers in de-identified operational scenarios. The purpose is not to collect patient locations or sensitive building plans. It is to identify representative tasks, exclusion conditions and receiving arrangements. A scenario should state where the aircraft could stop and which additional movement would be necessary."] },
      { title: "Observe the operator as well as the machine", paragraphs: ["Teleoperation makes operator information part of the capability. Cameras may have blind spots, lighting may change and a payload may obscure a view. Testing should record what the operator could see, how commands were issued and when uncertainty required a stop. Otherwise a mechanical demonstration can conceal an unrealistic level of support from nearby observers.", "An independent observer may help record events during a controlled exercise, but their assistance must be documented. If someone physically repositions the robot, supplies directions or removes an obstacle, that intervention changes the meaning of the result. Operator proficiency and practice time should also be recorded before comparing configurations."] },
      { title: "Treat communications as an environmental constraint", paragraphs: ["Ground movement can change the communication path after an aerial handoff. A mission that begins with a clear connection may enter a more difficult radio environment. NIST has published a test method addressing response-robot performance under attenuated radio conditions. That is a useful reference for making communication limitations part of a test rather than treating them as an unexpected exception.", "For the proposed MARDE workflow, questions include how the operator recognizes stale information, how movement stops and what recovery process is available. This article does not define a validated failsafe design. Those behaviors need engineering decisions and repeatable tests appropriate to the eventual hardware and control system."] },
      { title: "Measure task completion and recovery", paragraphs: ["A useful access test records whether the payload reaches the agreed receiving point, how long that takes and whether interventions occur. Recovery matters too: what happens when the route is blocked, the robot stops or a mission is abandoned? A task that succeeds only when nothing unexpected occurs provides limited evidence for an emergency-response use case.", "NIST ground-robot test methods offer a reference for structured evaluation. MARDE would need to select tasks relevant to its proposed workflow and identify which conditions were actually tested. Using a public method as inspiration does not imply certification, endorsement or successful completion of a formal evaluation."] },
      { title: "Connect access to the handoff", paragraphs: ["The final receiving point should be defined before testing. It might be a responder-controlled area or another designated location, depending on the intended use case. Reaching a patient is not automatically an appropriate or authorized objective. Clinical responsibility, equipment handling and responder access must remain explicit.", "An integrated evaluation should follow the payload from Air through Ground to receipt. It should record its condition after transport and whether a receiver understands the handoff. MARDE's proposed advantage is coordination of these steps; proving each component separately would leave the central integration question unanswered.", boundary] },
    ],
  },
  {
    slug: "research/human-oversight", title: "Human-in-the-loop robotics: define the decisions before the autonomy", description: "An evaluation framework for operator authorization, teleoperation and accountable system handoffs.", sources: [sources.nist, sources.radio],
    sections: [
      { title: "A label is not a control model", paragraphs: ["Human-in-the-loop can describe several arrangements: direct steering, approval of a proposed action or supervision of an automated sequence. A site should state which arrangement is intended rather than using the phrase as a general assurance. The relevant question is what a person can understand, authorize, interrupt and recover at each consequential step.", "MARDE V1 is intended to be operator-directed and teleoperated first. Nexus is the proposed coordination layer for mission review and transitions between Air, Ground and the payload handoff. Its website mockup illustrates an intended interface; it is not evidence that an operational authorization system exists."] },
      { title: "Identify consequential transitions", paragraphs: ["A requirements exercise can list transitions such as launch preparation, transport approval, ground release, final approach and handoff. For each, identify the responsible role, required information and conditions that make the action inappropriate. This produces a decision map that engineers and practitioners can review together.", "That map should distinguish an operator's movement command from a clinical decision. A person able to steer a robot is not necessarily authorized to decide how equipment should be used for a patient. Institutional responsibilities and professional scope must remain clear even when information appears in one shared interface."] },
      { title: "Make uncertainty visible", paragraphs: ["An operator needs to know whether information is current, incomplete or unavailable. A screen that presents stale data confidently may encourage a decision that the person would reject with better context. Requirements should identify the age and source of important status information, as well as how the interface signals communication loss.", "An approval control should not imply that every prerequisite has been checked unless the system can support that implication. The distinction between an operator assertion and an independently observed state matters. In a controlled exercise, reviewers should ask the operator to explain the basis for a decision rather than measuring button presses alone."] },
      { title: "Test stop and recovery paths", paragraphs: ["A workflow designed around successful completion is incomplete. Test an operator declining a mission, encountering an unexpected obstacle and stopping after a connection changes. Record what the interface shows, how control is recovered and whether other participants understand the mission state. These exercises can reveal ambiguity before a system enters a more demanding setting.", "Communication constraints deserve specific treatment. The NIST radio-condition publication is a reference for structured testing, not a guarantee that any particular control system will behave safely. MARDE must define and validate its own response to interrupted control and observation with the eventual hardware configuration."] },
      { title: "Evaluate workload and handoff clarity", paragraphs: ["An interface may be understandable in a quiet demonstration and confusing when several tasks compete for attention. Evaluation should consider alert volume, navigation burden, information switching and the time available to review a decision. If a second person supplies essential context during a test, record that staffing requirement rather than attributing it to the interface.", "The handoff record should help participants understand what happened and what remains unresolved. A successful transition is more than a state label changing color. The next responsible person needs enough context to accept control or decline it. Agency requirements should define what information is appropriate and which data should never be collected by a prototype exercise."] },
      { title: "Expand assistance only with evidence", paragraphs: ["Future assistance could reduce operator burden, but each function needs a clear task and evaluation. Guidance, obstacle warnings and automated movement have different implications. Evidence for one should not be used to imply readiness for all of them. The website should identify assistance as a future direction until the function and its limits are documented.", "For MARDE, the immediate commitment is to investigate an integrated, human-authorized workflow. Higher autonomy is conditional on engineering evidence and applicable evaluation, not a deployment promise. Researchers and agencies can use this decision-oriented framework to discuss requirements without assuming an operational product already exists.", boundary] },
    ],
  },
  {
    slug: "research/aviation-pathway", title: "Aviation readiness for an emergency robotics concept", description: "Separate aircraft engineering, operating permissions and agency integration when considering a future aerial response system.", sources: [sources.faa, sources.delivery],
    sections: [
      { title: "An emergency use case does not establish flight permission", paragraphs: ["An aircraft concept and a compelling public-safety purpose are not an operating authorization. A proposed mission must be evaluated against the applicable aviation framework and its actual conditions. MARDE has not claimed FAA approval, an operational delivery network or permission to integrate with emergency dispatch.", "The FAA's advanced-operations resources and package-delivery guidance are useful starting points for a requirements discussion. They describe different operational pathways and considerations. The existence of a pathway does not mean a particular MARDE configuration qualifies for it or that an agency can skip its own readiness assessment."] },
      { title: "Write the mission before choosing a pathway", paragraphs: ["A proposed mission description should identify the aircraft, payload, flight area, operating roles and expected conditions. It should also state whether the aircraft remains within visual line of sight, where people may be present and what happens after the payload reaches the scene. These details influence which questions need specialist review.", "MARDE's proposed Air component transports Ground and a payload. That combined configuration matters: its mass, retention arrangement and handoff behavior would need to be understood. A pathway selected for an unrelated drone or a different delivery arrangement cannot simply be copied onto an integrated system."] },
      { title: "Keep several readiness questions separate", paragraphs: ["Aircraft engineering asks whether the configuration performs as intended. Operational authorization asks whether a specified operation is permitted under applicable requirements. Agency integration asks whether staffing, dispatch, receiving and fallback arrangements are acceptable. Clinical evaluation asks different questions again. None of these should be treated as a substitute for the others.", "A controlled prototype demonstration can provide engineering evidence without establishing operational or clinical readiness. Its report should explain where it occurred, what permissions and constraints applied and which conclusions remain out of scope. A successful flight does not make a proposed EMS workflow approved."] },
      { title: "Package delivery guidance is context, not a shortcut", paragraphs: ["The FAA describes a Part 135 certification framework for drone package-delivery operations. Whether that framework is applicable to a future MARDE use case requires examination of the operation itself. This article does not classify MARDE's eventual missions or prescribe a legal pathway; the configuration and operating proposal are not yet validated.", "For planning, keep a register of unresolved regulatory questions and the facts needed to answer them. Record who is responsible for obtaining authoritative advice and when a decision must be made. That approach is more useful than putting an unsupported approval badge on a product concept page."] },
      { title: "Plan exclusions and alternative response", paragraphs: ["A credible operational proposal identifies conditions in which a flight will not take place. Weather, location uncertainty, unavailable receiving arrangements and system readiness can create different reasons to stop. Agencies need to understand how the conventional response continues when the robotic component is unavailable.", "Abort and recovery behavior should be investigated in controlled engineering exercises before being discussed as an established capability. Any eventual operating envelope should be connected to measured results and applicable authorization. Marketing language about rapid response should not erase exclusions or imply guaranteed availability."] },
      { title: "What MARDE can say today", paragraphs: ["MARDE can describe the architecture it is developing, the questions it intends to investigate and the public resources informing that work. It can invite practitioners to define requirements. It cannot presently provide a validated range, approved operational coverage, dispatch integration or a commercial deployment date.", "Before any future pilot, the team and relevant partners would need a defined operation, appropriate specialist review, a safety plan and a readiness decision supported by evidence. The sources below should be checked again when an actual operation is proposed because regulatory guidance can change. This article is a planning perspective, not legal advice about a specific flight.", boundary] },
    ],
  },
  {
    slug: "research/response-gap", title: "Reading CARES response-time data without overclaiming", description: "Registry response intervals explain a problem; they do not predict MARDE performance or clinical benefit.", sources: [sources.cares],
    sections: [
      { title: "Use the published definition", paragraphs: ["The MARDE homepage cites the 2024 CARES report for median first-responder and EMS response intervals of 6.4 and 7.6 minutes. These are registry findings about the population and definitions used in that report. They are not MARDE mission times, engineering targets or results from a robotics evaluation.", "The cited response analysis measures time from 911 call receipt to arrival on scene and excludes missing times and arrests witnessed by a 911 responder. Those definitions belong next to any use of the numbers. Removing the population or timestamp definition can make a precise statistic support a claim that its authors did not evaluate."] },
      { title: "A median is not a universal deadline", paragraphs: ["A median summarizes a distribution. It does not mean every call has the same response interval or that a new system would have that much time available. Local geography, staffing, scene characteristics and dispatch conditions may differ from the registry population. An agency evaluating a concept needs its own appropriately governed operational context.", "The distribution and missing-data pattern matter alongside the summary value. A proposed system could be relevant to a limited subset of situations rather than all calls in a registry. Requirements discovery should identify that subset before modeling coverage or expected benefit."] },
      { title: "Separate response from intervention", paragraphs: ["Arrival on scene does not necessarily coincide with arrival at a patient or the start of an intervention. Conversely, useful actions may occur before EMS arrives. The data definition determines what a response statistic can explain. It should not be used to fill in unmeasured intervals such as indoor access or payload retrieval.", "MARDE's proposed architecture investigates distance, access and coordination as connected tasks. That makes the distinction operationally relevant, but it does not establish that the design closes a measured gap. The team would need to record its own transport, access and handoff events under defined conditions."] },
      { title: "Do not subtract a concept from a registry median", paragraphs: ["It is tempting to subtract a projected flight duration from an EMS response median and call the difference time saved. That comparison combines observations from one population with an unvalidated estimate from another system. It also omits dispatch recognition, mission preparation, handoff and unsuccessful attempts.", "A more defensible early model would label every assumption, show sensitivity to changing conditions and distinguish modeled values from measured ones. Even then, it would support planning questions rather than a claim of clinical effectiveness. Once a configuration exists, measured exercise data can replace selected assumptions while keeping the remaining uncertainty explicit."] },
      { title: "Choose evaluation timestamps prospectively", paragraphs: ["A controlled integrated test can record request receipt, operator review, launch, arrival, ground transition, payload receipt and handoff completion. Definitions should be agreed before testing so the team does not choose favorable start or stop points afterward. Record interruptions and failed tasks, including where a timestamp cannot be observed.", "Comparisons should use equivalent events. Arrival at a landing location and arrival at a patient are not interchangeable. Different baselines may be appropriate for engineering, agency operations and clinical research. Qualified evaluators should select endpoints that match the actual decision being considered."] },
      { title: "Connect the problem statement to the next evidence", paragraphs: ["CARES provides a reference for explaining why the interval before professional arrival deserves investigation. It does not prove a particular robotic architecture is useful. MARDE's next evidence needs to come from building the system, investigating handoffs and documenting the limits of an integrated human-operated demonstration.", "Readers should inspect the cited report rather than treating a homepage statistic as the full analysis. Agencies can discuss de-identified workflow constraints through the EMS Partners and Contact pages. No patient data is needed to explain an initial access problem or define a controlled requirements exercise.", boundary] },
    ],
  },
  {
    slug: "research/evaluating-early-stage-partners", title: "How EMS agencies can evaluate an early-stage robotics partner", description: "A requirements-first framework for separating a credible research conversation from deployment readiness.", sources: [sources.nist, sources.faa],
    sections: [
      { title: "Start by identifying the development stage", paragraphs: ["An early-stage company can contribute ideas and engineering work without offering an operational product. An agency should ask what exists today, what has been tested and what remains a design objective. A clear answer is more useful than a polished demonstration that leaves the configuration and limits unstated.", "MARDE is pre-seed, pre-prototype and pre-revenue. Its immediate goal is an integrated human-in-the-loop V1 demonstration. There are no announced commercial pilots or validated full-system results. A conversation with MARDE should therefore begin with research questions and requirements rather than procurement of a ready emergency-response service."] },
      { title: "Define the agency problem independently", paragraphs: ["Write the operational problem before adopting the vendor's proposed architecture. Identify the relevant setting, receiving role, access barriers and existing alternatives. A useful problem statement explains what improvement would matter and which constraints cannot be changed. It also identifies situations where the concept would not be appropriate.", "Requirements discovery can use de-identified scenarios and general conditions. Patient records, sensitive access details and production-system credentials are not necessary for a first discussion. Agencies should preserve their own information-governance requirements as the conversation becomes more specific."] },
      { title: "Ask for a claim-to-evidence map", paragraphs: ["For each proposed capability, ask whether it is a goal, an observed bench result, an integrated exercise result or an operational outcome. Request the configuration, conditions, number of attempts and intervention record. A video can illustrate an event but rarely supplies the full denominator or repeatability information.", "The company should be able to identify which conclusions change if hardware, payload, software or environment changes. External literature can inform the concept but should not be presented as evidence that the company's own system works. An agency can make this distinction a routine part of review rather than an adversarial demand."] },
      { title: "Design a small, bounded exercise", paragraphs: ["An early exercise should answer a limited question under controlled conditions. Agree on success criteria, stopping rules, roles and reporting before the test. Include cases in which an operator declines or interrupts the mission. Record failures and recovery so the result describes the workflow rather than a selected successful attempt.", "NIST response-robot methods can help frame repeatable task evaluation. The actual method selection needs to match the proposed use case. A test inspired by a published method should not be represented as formal certification, and a subsystem result should not be promoted into clinical or deployment readiness."] },
      { title: "Keep responsibilities and approvals explicit", paragraphs: ["A future evaluation may involve aircraft operation, ground control, payload receipt and clinical responsibility. Identify who owns each decision and what happens if the system is unavailable. The agency should understand the staffing and training assumptions rather than discovering them during an exercise.", "Any eventual operational pilot requires separate review of applicable permissions, safety, data handling and institutional obligations. FAA resources are a starting point for aviation questions, not approval of a vendor or mission. A research conversation should not silently create a promise of dispatch integration, equipment purchase or clinical use."] },
      { title: "Look for honest reporting and a useful next step", paragraphs: ["A credible early-stage partner reports what it could not demonstrate and changes its claims when evidence changes. Ask how revisions are dated, how unsuccessful attempts are described and how agency feedback changes requirements. Progress is more informative when the company identifies the next unresolved question rather than repeating a fixed launch promise.", "For MARDE, the appropriate starting point is a requirements discussion through the Contact page. Share the institutional role and the access or coordination problem you want to explore. Any later evaluation would need a separately agreed scope. This page does not list existing partners, endorsements or availability for live emergency response.", boundary] },
    ],
  },
].map(page => ({ ...page, sections: [...page.sections.slice(0, -1), ...researchExercises[page.slug], ...page.sections.slice(-1)], kind: "research", published: "2026-10-01", author: "MARDE Inc." }));
