import Image from "next/image";
import Link from "next/link";
import { pageMetadata } from "../metadata";
import { Editorial, PageIntro, Closing } from "../../components/v2/editorial";
import { Arrow } from "../../components/v2/primitives";
import { teamProfiles } from "../../lib/content/profiles";
import s from "../../components/v2/editorial.module.css";
export const metadata=pageMetadata({title:"MARDE Team | Engineering, Care & Coordination",description:"Meet the five-person MARDE team working across aerial engineering, software, clinical workflow research and community outreach.",path:"/team"});
export default function TeamPage(){return <Editorial><PageIntro eyebrow="THE PEOPLE BEHIND MARDE" title={<>Different disciplines.<br/><span>A shared direction.</span></>} text="A five-person team bringing software, aerial engineering, clinical workflow research and community outreach to one developing response platform."/><section className={s.teamList} aria-label="MARDE team">{teamProfiles.map(person=><article className={s.member} key={person.slug}><div className={s.memberPhoto}>{person.portrait?<Image unoptimized src={person.portrait} alt={person.name} width={300} height={300}/>:<span aria-hidden="true">{person.initials}</span>}</div><div><p className={s.role}>{person.role}</p><h2>{person.name}</h2><p>{person.bio}</p><Link className={s.textLink} href={`/${person.slug}/`} aria-label={`Open ${person.name}'s digital contact card`}>Connect<Arrow/></Link></div><ul className={s.credentials} aria-label={`Selected experience of ${person.name}`}>{person.credentials.map(item=><li key={item}>{item}</li>)}</ul></article>)}</section><Closing title="Bring your perspective." text="We welcome conversations with engineers, researchers, EMS and public-safety teams who can help us ask better questions and test the right things."/></Editorial>;}
