import { pageMetadata } from "../metadata";
import { Editorial, PageIntro } from "../../components/v2/editorial";
import s from "../../components/v2/editorial.module.css";
export const metadata=pageMetadata({title:"Privacy Policy | MARDE",description:"How information is handled by the MARDE website, contact form, payments, scheduling and digital contact cards.",path:"/privacy"});
export default function PrivacyPage(){return <Editorial><PageIntro eyebrow="PRIVACY" title={<>Your information.<br/><span>A clear explanation.</span></>} text="What this website collects, the services it connects to and how to reach us about your information."/><article className={s.policy}><p className={s.updated}>LAST UPDATED / SEPTEMBER 9, 2026</p>
<h2>Information you choose to provide</h2><p>The Contact form sends your name, organization, email address, inquiry category and message to MARDE through Formspree. We use that information to respond and manage the conversation you requested. Please do not submit patient records, medical details or other sensitive personal information.</p>
<h2>Payments through Stripe</h2><p>Support links open Stripe’s hosted payment page. Stripe processes your payment information; this website does not collect or store card details. Stripe’s own privacy policy and terms apply to its service.</p>
<h2>Scheduling a conversation</h2><p>On Nandish’s digital contact card, opening Schedule loads a Calendly page inside a dialog. Calendly may receive technical information such as your IP address and browser details when it loads, and any booking details you choose to submit. It may use cookies under its own policies. The scheduler is not loaded before you open it. You can also open the scheduling page directly.</p>
<h2>Digital contact cards and sharing</h2><p>Public contact cards display approved professional information. Add to Contacts downloads a vCard to your device; your contacts are not read or uploaded. Share uses your device’s sharing feature when available, or copies the profile URL to your clipboard. You choose whether and where to share it.</p>
<h2>Analytics and browser storage</h2><p>When a Google Analytics measurement ID is configured, the main website loads Google Analytics to understand aggregate usage and selected interactions. Google may use cookies or similar technologies under its policies. Without a configured ID, that analytics script is not loaded. The standalone contact cards do not load the main site’s analytics integration.</p><p>Campaign parameters in a URL may be stored in session storage for the current browser session and included in analytics events when analytics is configured. We do not add these parameters to internal links. Contact-form text is not included in our analytics events.</p>
<h2>Hosting and external services</h2><p>The website is hosted on GitHub Pages, with Cloudflare-managed domain services. Hosting and network providers may process technical request information to deliver and protect the site. Fonts and website images are served with the site. Visiting external links, including social networks and the Canva pitch deck, connects you to services governed by their own policies.</p>
<h2>Retention and your choices</h2><p>Submitted information is kept as reasonably needed for the conversation, operational records and applicable obligations. You may ask about, correct or request deletion of information you submitted by emailing <a href="mailto:team@mardeinc.com">team@mardeinc.com</a>. Some records may need to be retained for legal or legitimate recordkeeping purposes.</p>
<h2>Changes to this page</h2><p>We update this explanation when the website or the services it uses change. The latest version appears here with its revision date.</p></article></Editorial>;}
