export const nandishProfile = {
  slug: "nandish",
  name: "Nandish Panchal",
  title: "Founder & CEO",
  company: "MARDE, Inc.",
  email: "marde.nandish@gmail.com",
  phone: "+18482399831",
  portrait: "/team/nandish-panchal.webp",
  portraitAlt: "Nandish Panchal, Founder and CEO of MARDE",
  companyUrl: "https://mardeinc.com",
  profileUrl: "https://mardeinc.com/nandish",
  vcardUrl: "/contacts/nandish.vcf",
  linkedin: "https://www.linkedin.com/in/nandish-panchal-4aab2b340/",
  schedule: "https://calendly.com/nandishmarde/30",
  github: "https://github.com/Nandish-GH/",
  shareTitle: "Nandish Panchal — MARDE",
  shareText: "Nandish Panchal, Founder & CEO of MARDE",
} as const;
