import { pageMetadata } from "../metadata";
import { Editorial, PageIntro, Closing } from "../../components/v2/editorial";
import { Kicker } from "../../components/v2/primitives";
import { ProductGraphic } from "../../components/v2/product-graphic";
import { SystemArt } from "../../components/v2/system-art";
import { NexusConcept, ResponseSequence } from "../../components/v2/interactions";
import s from "../../components/v2/editorial.module.css";
export const metadata = pageMetadata({title:"MARDE Technology | Air, Ground, Nexus & Modules",description:"Explore MARDE’s integrated emergency-response concept: aerial transport, teleoperated ground access, human coordination and adaptable payloads.",path:"/technology"});
export default function TechnologyPage(){return <Editorial>
<PageIntro eyebrow="THE MARDE PLATFORM" title={<>Distance. Access.<br/><span>One coordinated system.</span></>} text="Air, Ground, Nexus and Modules are being developed together to extend useful response capability toward the patient before EMS arrives."/>
<div className={s.jump} aria-label="Technology sections">{["Air","Ground","Nexus","Modules"].map((name,i)=><a href={`#${name.toLowerCase()}`} key={name}><span>0{i+1}</span>{name} ↓</a>)}</div>
<section className={`${s.section} ${s.dark} ${s.split}`}><div className={s.copy}><Kicker number="01">INTEGRATED BY DESIGN</Kicker><h2>Arrival is a start.<br/>Access is the next step.</h2><p>Emergency drones demonstrate the value of rapid aerial response. MARDE is exploring what happens after that arrival: a coordinated ground approach, directed by a human operator, carrying the response payload closer.</p><p>Each part has a distinct job. Nexus connects them into a workflow designed to complement professional responders.</p></div><SystemArt/></section>
<section id="air" className={`${s.section} ${s.split}`}><div className={s.copy}><Kicker number="02">MARDE AIR / DISTANCE</Kicker><h2>Move the response<br/>toward the scene.</h2><p className={s.lead}>Aerial transport for the integrated Ground and payload system.</p><p>Air V1 is in engineering development. Its role is to carry the response system toward the emergency, with operator authorization built into the intended workflow.</p><ul><li>Transport within a coordinated mission</li><li>Planned Air–Ground handoff</li><li>Geometry and performance to be validated</li></ul></div><ProductGraphic type="air"/></section>
<section id="ground" className={`${s.section} ${s.blueprint} ${s.split} ${s.reverse}`}><div className={s.copy}><Kicker number="03">MARDE GROUND / ACCESS</Kicker><h2>Continue beyond<br/>aerial arrival.</h2><p className={s.lead}>The final approach is a ground problem.</p><p>Ground V1 is intended to move toward the patient where the aircraft cannot directly reach. A trained operator directs that approach. Terrain, stairs and constrained spaces are design considerations to investigate through engineering and testing.</p><ul><li>Teleoperated first</li><li>Integrated response payload</li><li>Final-access capability remains a design objective</li></ul></div><ProductGraphic type="ground"/></section>
<section id="nexus" className={`${s.section} ${s.dark}`}><Kicker number="04">MARDE NEXUS / COORDINATION</Kicker><div className={s.wideHeading}><h2>Human control.<br/>A shared view.</h2><p>Nexus is the planned command layer for mission context, system readiness, operator authorization and the handoff between Air, Ground and EMS.</p></div><NexusConcept/><div className={s.wideHeading}><h3>Authorization is part of the architecture.</h3><p>The underlying software is still in development. Nexus V1 is not an autonomous medical decision system. Consequential actions remain with trained operators.</p></div></section>
<section id="modules" className={`${s.section} ${s.split}`}><div className={s.copy}><Kicker number="05">INTERVENTION MODULES / CAPABILITY</Kicker><h2>A platform built<br/>to carry more purpose.</h2><p className={s.lead}>Adaptable payloads, coordinated with the response.</p><p>Near-term development focuses on delivery, secure-response functions and payload integration. The modular concept leaves room for future capabilities as evidence and requirements develop.</p><p>Advanced medical modules would require further engineering, clinical, operational and regulatory validation. They are not current MARDE treatment capabilities.</p></div><ProductGraphic type="modules"/></section>
<section className={`${s.section} ${s.dark}`}><Kicker number="06">THE INTENDED V1 WORKFLOW</Kicker><div className={s.wideHeading}><h2>From dispatch<br/>to professional care.</h2><p>One conceptual sequence. Clear responsibility at every transition.</p></div><ResponseSequence dark/></section>
<section className={s.section}><Kicker number="07">EVIDENCE BEFORE EXPANSION</Kicker><div className={s.wideHeading}><h2>Build. Integrate.<br/>Then prove the workflow.</h2><p>Our next milestone is an integrated human-in-the-loop demonstration of Air V1, Ground V1 and Nexus V1. We are pre-prototype, with no validated full-system performance or commercial pilots.</p></div><ol className={s.progression}><li><span>V1 / DEVELOPMENT FOCUS</span><h3>Human-directed</h3><p>Operator review, teleoperation and controlled system integration.</p></li><li><span>FOLLOWING VALIDATION</span><h3>Assisted operation</h3><p>Explore assistance that can be evaluated against measured reliability and operator needs.</p></li><li><span>LONGER-TERM DIRECTION</span><h3>Progressive autonomy</h3><p>Expand only as engineering evidence, operational evaluation and applicable approvals support it.</p></li></ol></section><Closing/>
</Editorial>;}
